language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 5.6

install: composer update

script: vendor/bin/phpunit -v
